version: '3.4'
services:
    bar-nginx:
        build:
            context: ./bar/docker
            dockerfile: nginx.docker
        volumes:
            - ./bar:/var/www/html
        depends_on:
            - bar-php-fpm
        ports:
            - "8080:80"
    bar-php-fpm:
        build:
            context: ./bar/docker
            dockerfile: php-fpm.docker
        volumes:
            - ./bar:/var/www/html
        depends_on:
            - bar-mysql
    bar-php-cli:
        build:
            context: ./bar/docker
            dockerfile: php-cli.docker
        volumes:
            - ./bar:/var/www/html
            - composer:/root/.composer/cache
        depends_on:
            - bar-mysql
    bar-mysql:
        image: mysql:5.7
        volumes:
            - bar-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: app_db
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_password
        ports:
            - "33306:3306"

volumes:
    bar-mysql:
    composer:
